CREATE TABLE `ceci_corp_base` (
  `t_date` datetime DEFAULT NULL COMMENT '变动日期',
  `corp_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '企业编号',
  `controller` int(11) DEFAULT NULL COMMENT '控制人编号',
  `corp_name` varchar(100) DEFAULT NULL COMMENT '企业名称',
  `artificial_person` varchar(50) DEFAULT NULL COMMENT '企业法人',
  `corp_bln` varchar(100) DEFAULT NULL COMMENT '营业执照号码',
  `corp_type` varchar(255) DEFAULT NULL COMMENT '公司类型',
  `corp_bs` varchar(2000) DEFAULT NULL COMMENT '经营范围',
  `corp_rc` decimal(20,4) DEFAULT NULL COMMENT '注册资本（万元）',
  `corp_pc` decimal(20,4) DEFAULT NULL COMMENT '实收资本',
  `currency_code` varchar(10) DEFAULT NULL COMMENT '货币代码',
  `corp_edate` date DEFAULT NULL COMMENT '企业成立日期',
  `corp_addr` varchar(500) DEFAULT NULL COMMENT '注册地址',
  `corp_rdate` date DEFAULT NULL COMMENT '注册登记日期',
  `corp_ddate` date DEFAULT NULL COMMENT '注册登记到期日',
  `register_org` varchar(100) DEFAULT NULL COMMENT '登记机关',
  `approval_date` date DEFAULT NULL COMMENT '核准日期',
  `approval_status` varchar(50) DEFAULT NULL COMMENT '核准状态',
  `industry_category` varchar(6) DEFAULT NULL COMMENT '行业分类',
  `org_id` varchar(20) DEFAULT NULL COMMENT '组织机构代码',
  `tax_id` varchar(20) DEFAULT NULL COMMENT '税务登记证号',
  `company_ID` varchar(300) DEFAULT NULL COMMENT '工商总局企业ID',
  `zhejiang_id` char(100) DEFAULT NULL COMMENT '浙江企业id',
  `get_date` date DEFAULT NULL COMMENT '抓取日期',
  `res_date` varchar(100) DEFAULT NULL COMMENT '数据来源',
  `canc_date` date DEFAULT NULL COMMENT '注销日期',
  `quantum_id` varchar(255) DEFAULT NULL COMMENT '量子id',
  PRIMARY KEY (`corp_id`)
) COMMENT='企业基本信息_产品部'
